# Project 1

In this first project you will create a framework to scope out data science projects. This framework will provide you with a guide to develop a well-articulated problem statement and analysis plan that will be robust and reproducible.

### Read and evaluate the following problem statement: 
Determine which free-tier customers will covert to paying customers, using demographic data collected at signup (age, gender, location, and profession) and customer useage data (days since last log in, and activity score 1 = active user, 0= inactive user) based on Hooli data from Jan-Apr 2015.

#### 1. What is the outcome?

Answer: Shows which free tier customers will convert to paying customers

#### 2. What are the predictors/covariates?

Answer: 
* Customer Demographic Data: Age, Gender, Location & Professions and; 
* Customer Usage Data: Days since log in & activity score.

#### 3. What timeframe is this data relevent for?

Answer: January 2015 - April 2015

#### 4. What is the hypothesis?

Answer: Customers who logged in most recently and have an activity score of 1 are more likely to convert from free-tier customers to paying customers

## Let's get started with our dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
admission_data = pd.read_csv('../assets/admissions.csv')

In [4]:
admission_data.head()

   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0

#### 1. Create a data dictionary

In [10]:
admission_data.sort_values(by='gre')

     admit    gre   gpa  prestige
304      0  220.0  2.83       3.0
179      0  300.0  3.01       3.0
71       0  300.0  2.92       4.0
315      1  300.0  2.84       2.0
216      0  340.0  2.90       1.0
316      1  340.0  3.00       2.0
100      0  340.0  3.15       3.0
119      0  340.0  2.92       3.0
17       0  360.0  2.56       3.0
281      0  360.0  3.27       3.0
112      0  360.0  3.00       3.0
34       0  360.0  3.14       1.0
102      0  380.0  3.33       4.0
265      0  380.0  3.34       3.0
83       0  380.0  2.91       4.0
145      0  380.0  3.43       3.0
232      0  380.0  3.38       2.0
193      0  380.0  3.59       4.0
57       0  380.0  2.94       3.0
0        0  380.0  3.61       3.0
302      1  400.0  3.15       2.0
348      0  400.0  3.36       2.0
151      0  400.0  3.38       2.0
108      0  400.0  2.93       3.0
7        0  400.0  3.08       2.0
58       0  400.0  3.65       2.0
197      1  400.0  3.23       4.0
99       0  400.0  3.31       3.0
170      0  400.0  3.51       3.0
49       0  400.0  3.35       3.0
..     ...    ...   ...       ...
16       0  780.0  3.87       4.0
317      1  780.0  3.63       4.0
350      1  780.0  4.00       2.0
200      0  800.0  3.31       3.0
191      0  800.0  3.54       3.0
224      0  800.0  2.90       2.0
150      1  800.0  3.74       1.0
390      1  800.0  3.05       2.0
234      1  800.0  3.53       1.0
2        1  800.0  4.00       1.0
173      1  800.0  3.43       2.0
223      0  800.0  3.47       3.0
69       0  800.0  3.73       1.0
286      1  800.0  3.22       1.0
10       0  800.0  4.00       4.0
33       1  800.0  4.00       3.0
245      0  800.0  3.91       3.0
92       0  800.0  3.90       2.0
185      0  800.0  3.60       2.0
377      1  800.0  4.00       2.0
293      0  800.0  3.97       1.0
18       0  800.0  3.75       2.0
291      0  800.0  2.78       2.0
288      0  800.0  3.15       4.0
118      1  800.0  3.70       1.0
369      0  800.0  3.89       2.0
77       1  800.0  4.00       3.0
25       1  800.0  3.66       1.0
187      0    NaN   NaN       2.0
212      0    NaN  2.87       2.0

[400 rows x 4 columns]

In [11]:
admission_data.sort_values(by='gpa')

     admit    gre   gpa  prestige
289      0  420.0  2.26       4.0
40       0  560.0  2.42       2.0
372      1  680.0  2.42       1.0
48       0  440.0  2.48       4.0
156      0  560.0  2.52       2.0
294      0  480.0  2.55       1.0
17       0  360.0  2.56       3.0
176      0  520.0  2.62       2.0
384      1  480.0  2.62       2.0
397      0  460.0  2.63       2.0
341      1  560.0  2.65       3.0
121      1  480.0  2.67       2.0
233      0  420.0  2.67       3.0
39       1  520.0  2.68       3.0
323      0  420.0  2.69       2.0
324      0  520.0  2.70       3.0
379      0  540.0  2.70       2.0
82       0  500.0  2.71       2.0
147      0  560.0  2.71       3.0
163      0  520.0  2.73       2.0
240      0  440.0  2.76       2.0
291      0  800.0  2.78       2.0
365      0  480.0  2.78       3.0
184      0  500.0  2.79       4.0
131      0  640.0  2.79       2.0
269      0  500.0  2.81       3.0
355      1  760.0  2.81       1.0
171      0  540.0  2.81       3.0
22       0  600.0  2.82       4.0
59       0  600.0  2.82       4.0
..     ...    ...   ...       ...
33       1  800.0  4.00       3.0
330      0  740.0  4.00       3.0
12       1  760.0  4.00       1.0
383      0  660.0  4.00       1.0
10       0  800.0  4.00       4.0
395      0  620.0  4.00       2.0
2        1  800.0  4.00       1.0
14       1  700.0  4.00       1.0
55       1  740.0  4.00       3.0
73       0  580.0  4.00       2.0
64       0  580.0  4.00       3.0
360      1  520.0  4.00       1.0
168      0  500.0  4.00       3.0
137      0  700.0  4.00       3.0
350      1  780.0  4.00       2.0
182      0  700.0  4.00       2.0
368      0  580.0  4.00       1.0
202      1  700.0  4.00       1.0
89       1  660.0  4.00       2.0
79       1  620.0  4.00       1.0
237      0  480.0  4.00       2.0
77       1  800.0  4.00       3.0
75       0  720.0  4.00       3.0
377      1  800.0  4.00       2.0
165      0  700.0  4.00       1.0
70       0  640.0  4.00       3.0
252      1  520.0  4.00       2.0
310      0  560.0  4.00       3.0
187      0    NaN   NaN       2.0
236      1  660.0   NaN       NaN

[400 rows x 4 columns]

In [12]:
admission_data.sort_values(by='prestige')

     admit    gre   gpa  prestige
126      1  600.0  3.54       1.0
234      1  800.0  3.53       1.0
338      0  540.0  3.20       1.0
113      0  600.0  3.22       1.0
217      1  460.0  3.64       1.0
106      1  700.0  3.56       1.0
91       1  720.0  3.64       1.0
88       0  700.0  3.28       1.0
241      1  520.0  3.81       1.0
79       1  620.0  4.00       1.0
118      1  800.0  3.70       1.0
78       0  540.0  3.12       1.0
357      0  720.0  3.31       1.0
360      1  520.0  4.00       1.0
69       0  800.0  3.73       1.0
68       0  580.0  3.69       1.0
67       0  620.0  3.30       1.0
361      1  540.0  3.49       1.0
364      1  560.0  3.36       1.0
244      0  540.0  3.04       1.0
368      0  580.0  4.00       1.0
355      1  760.0  2.81       1.0
372      1  680.0  2.42       1.0
335      1  620.0  3.71       1.0
325      0  680.0  3.90       1.0
216      0  340.0  2.90       1.0
273      0  660.0  3.32       1.0
207      1  640.0  3.63       1.0
206      0  740.0  3.54       1.0
277      1  580.0  3.58       1.0
..     ...    ...   ...       ...
238      0  500.0  2.86       4.0
250      0  660.0  3.31       4.0
251      0  620.0  3.21       4.0
174      0  500.0  3.53       4.0
305      0  580.0  3.46       4.0
166      0  440.0  3.24       4.0
155      1  580.0  2.86       4.0
102      0  380.0  3.33       4.0
110      0  680.0  3.08       4.0
342      0  500.0  3.95       4.0
111      0  420.0  3.41       4.0
340      0  500.0  3.23       4.0
337      0  620.0  3.09       4.0
125      0  540.0  3.38       4.0
127      0  740.0  3.74       4.0
329      0  500.0  2.93       4.0
83       0  380.0  2.91       4.0
129      0  460.0  3.15       4.0
136      0  560.0  3.33       4.0
141      1  700.0  3.52       4.0
322      0  500.0  3.01       4.0
142      0  620.0  3.94       4.0
144      0  580.0  3.40       4.0
318      1  480.0  3.71       4.0
317      1  780.0  3.63       4.0
314      0  540.0  3.46       4.0
313      1  520.0  3.65       4.0
254      1  740.0  3.52       4.0
199      0  580.0  3.77       4.0
236      1  660.0   NaN       NaN

[400 rows x 4 columns]

Answer: 

Variable | Description | Type of Variable
---| ---| ---
Admit | 0 = Not Admitted 1 = Admitted | categorical
gre | 220 - 800 | continuous 
gpa | 2.26 - 4.00 | continuous 
prestige | 1-not prestigious 2-somewhat prestiguous 3-prestigous 4-very prestigous | categorical

We would like to explore the association between X and Y

#### 2. What is the outcome?

Answer: Shows who will be admitted

#### 3. What are the predictors/covariates?

Answer: GRE score, GPA, and level of prestige

#### 4. What timeframe is this data relevent for?

Answer: There is not clear details on the timeframe in which the dataset was taken

#### 4. What is the hypothesis?

Answer: If you have are at a high level of prestige, a high GPA and high GRE score you have a higher likeihood of being admitted.

    Using the above information, write a well-formed problem statement.

## Problem Statement

### Exploratory Analysis Plan

Using the lab from a class as a guide, create an exploratory analysis plan.

#### 1. What are the goals of the exploratory analysis?

Answer:

#### 2a. What are the assumptions of the distribution of data?

Answer:

#### 2b. How will determine the distribution of your data?

Answer:

#### 3a. How might outliers impact your analysis?

Answer:

#### 3b. How will you test for outliers?

Answer:

#### 4a. What is colinearity?

Answer:

#### 4b. How will you test for colinearity?

Answer:

#### 5. What is your exploratory analysis plan?
Using the above information, write an exploratory analysis plan that would allow you or a colleague to reproduce your analysis 1 year from now.

Answer:

## Bonus Questions:
1. Outline your analysis method for predicting your outcome
2. Write an alternative problem statement for your dataset
3. Articulate the assumptions and risks of the alternative model